# Generated by Django 4.2.4 on 2023-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_ticket_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
