# Generated by Django 4.2.4 on 2023-08-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0004_artist_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Birthdate Or Created Band'),
        ),
    ]
