# Generated by Django 4.2.4 on 2023-08-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_artist_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='capp.artist', verbose_name='Artist'),
        ),
    ]
